version: 1.0.10.{build}

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: clang-cl
      generator: Ninja
      build_group: Experimental
      msvc_setup_path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      msvc_setup_arg: x86_amd64
    - compiler: msvc
      generator: Visual Studio 15 2017 Win64
      build_group: Continuous

matrix:
  allow_failures:
    - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += ";C:\third_party\installs\Ninja;C:\Program Files\PostgreSQL\10\bin\;"
  - ps: $env:CMAKE_TOOLCHAIN_FILE = "c:\third_party\installs\vcpkg-export\scripts\buildsystems\vcpkg.cmake"
  - ps: $env:VCPKG_TARGET_TRIPLET = "x64-windows-static"
  - ps: $env:PreferredToolArchitecture = "x64"

services:
  - postgresql101

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET POSTGRES_SERVER_SETUP=1
  - psql -f build\scripts\setup_postgres.sql -U postgres
  - if DEFINED msvc_setup_path call "%msvc_setup_path%" %msvc_setup_arg%
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: $env:BUILD_PROVIDER = "appveyor"
  - ps: cd $project_dir
  - ps: ctest --extra-verbose --script ".ctest.cmake,configuration_type=$env:configuration,generator=$env:generator,compiler=$env:compiler,build_group=$env:build_group";

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/558942cd80151ffa05dd
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
