version: 1.0.9.{build}

branches:
    only:
        - master

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: clang-cl
    - compiler: msvc

matrix:
  allow_failures:
    - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += ";C:\third_party\installs\Ninja"
  - ps: $env:CMAKE_TOOLCHAIN_FILE = "c:\third_party\installs\vcpkg-export\scripts\buildsystems\vcpkg.cmake"

before_build:
  - if DEFINED MSVC_SETUP_PATH call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: $build_type="$env:configuration";
  - ps: $compiler = $env:compiler;
  - ps: if ($compiler -eq "msvc") {
            $target = "ALL_BUILD run_windows_green_tests";
        } elseif ($compiler -eq "clang-cl") {
            $target = "all run_windows_green_tests";
        }
  - ps: cd $project_dir
  - ps: .\build\scripts\build.windows.ps1 -build_type $build_type -compiler $compiler -target $target

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/558942cd80151ffa05dd
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
