version: 1.0.9.{build}

branches:
    only:
        - master

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: msvc
    - compiler: clang-cl

matrix:
  allow_failures:
    - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += "c:\third_party\installs\ninja\bin"

build_script:
  - ps: $build_type="$env:configuration";
  - ps: $target = "ALL_BUILD";
  - ps: cd $project_dir
  - ps: $compiler = $env:compiler;
  - ps: .\build\scripts\build.windows.ps1 -build_type $build_type -compiler $compiler -target $target

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/558942cd80151ffa05dd
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
