#!/bin/bash

#
# Quick hack to rename files generated by converter. The problem at
# the moment is that filenames with multiple extensions don't work too
# well with CMake. So, to make things easier, we end up generating
# incorrect file names from conversion, and then massage them using
# this script.
#
# To convert models:
# - delete all JSON models: rm *json
# - execute ca target
# - run this script.
# - run iaj target

mv cpp_ref_impl.boost_model.dia.json cpp_ref_impl.boost_model.json
mv cpp_ref_impl.colours.dia.json cpp_ref_impl.colours.json
mv cpp_ref_impl.compressed.dia.json cpp_ref_impl.compressed.json
mv cpp_ref_impl.cpp_98.dia.json cpp_ref_impl.cpp_98.json
mv cpp_ref_impl.cpp_model.dia.json cpp_ref_impl.cpp_model.json
mv cpp_ref_impl.directory_settings.dia.json cpp_ref_impl.directory_settings.json
mv cpp_ref_impl.disable_cmakelists.dia.json cpp_ref_impl.disable_cmakelists.json
mv cpp_ref_impl.disable_facet_folders.dia.json cpp_ref_impl.disable_facet_folders.json
mv cpp_ref_impl.enable_facet_hash.dia.json cpp_ref_impl.enable_facet_hash.json
mv cpp_ref_impl.enable_facet_io.dia.json cpp_ref_impl.enable_facet_io.json
mv cpp_ref_impl.enable_facet_serialization.dia.json cpp_ref_impl.enable_facet_serialization.json
mv cpp_ref_impl.enable_facet_types.dia.json cpp_ref_impl.enable_facet_types.json
mv cpp_ref_impl.flat_directory_mode.dia.json cpp_ref_impl.flat_directory_mode.json
mv cpp_ref_impl.lam_model.dia.json cpp_ref_impl.lam_model.json
mv cpp_ref_impl.northwind.dia.json cpp_ref_impl.northwind.json
mv cpp_ref_impl.split_project.dia.json cpp_ref_impl.split_project.json
mv cpp_ref_impl.std_model.dia.json cpp_ref_impl.std_model.json
mv cpp_ref_impl.two_layers_with_objects.dia.json cpp_ref_impl.two_layers_with_objects.json
