// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "masd.cpp_ref_impl.northwind/odb/categories-odb-sqlite.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // categories
  //

  struct access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::id_type
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::init (
        id,
        i.category_id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // category_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::grow (
          i.category_id_value, t + 0UL))
      grew = true;

    // category_name_
    //
    if (t[1UL])
    {
      i.category_name_value.capacity (i.category_name_size);
      grew = true;
    }

    // description_
    //
    if (t[2UL])
    {
      i.description_value.capacity (i.description_size);
      grew = true;
    }

    // picutre_
    //
    if (t[3UL])
    {
      i.picutre_value.capacity (i.picutre_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // category_id_
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::bind (
        b + n, i.category_id_value, sk);
      n += 1UL;
    }

    // category_name_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.category_name_value.data ();
    b[n].size = &i.category_name_size;
    b[n].capacity = i.category_name_value.capacity ();
    b[n].is_null = &i.category_name_null;
    n++;

    // description_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.description_value.data ();
    b[n].size = &i.description_size;
    b[n].capacity = i.description_value.capacity ();
    b[n].is_null = &i.description_null;
    n++;

    // picutre_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.picutre_value.data ();
    b[n].size = &i.picutre_size;
    b[n].capacity = i.picutre_value.capacity ();
    b[n].is_null = &i.picutre_null;
    n++;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    sqlite::statement_kind sk (sqlite::statement_select);
    composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // category_id_
    //
    if (sk == statement_insert)
    {
      ::masd::cpp_ref_impl::northwind::category_id const& v =
        o.category_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::init (
        i.category_id_value,
        v,
        sk);
    }

    // category_name_
    //
    {
      ::std::string const& v =
        o.category_name ();

      bool is_null (false);
      std::size_t cap (i.category_name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.category_name_value,
        i.category_name_size,
        is_null,
        v);
      i.category_name_null = is_null;
      grew = grew || (cap != i.category_name_value.capacity ());
    }

    // description_
    //
    {
      ::std::string const& v =
        o.description ();

      bool is_null (true);
      std::size_t cap (i.description_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.description_value,
        i.description_size,
        is_null,
        v);
      i.description_null = is_null;
      grew = grew || (cap != i.description_value.capacity ());
    }

    // picutre_
    //
    {
      ::std::string const& v =
        o.picutre ();

      bool is_null (true);
      std::size_t cap (i.picutre_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.picutre_value,
        i.picutre_size,
        is_null,
        v);
      i.picutre_null = is_null;
      grew = grew || (cap != i.picutre_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // category_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::category_id& v =
        o.category_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::init (
        v,
        i.category_id_value,
        db);
    }

    // category_name_
    //
    {
      ::std::string& v =
        o.category_name ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.category_name_value,
        i.category_name_size,
        i.category_name_null);
    }

    // description_
    //
    {
      ::std::string& v =
        o.description ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.description_value,
        i.description_size,
        i.description_null);
    }

    // picutre_
    //
    {
      ::std::string& v =
        o.picutre ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.picutre_value,
        i.picutre_size,
        i.picutre_null);
    }
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    sqlite::statement_kind sk (sqlite::statement_select);
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::category_id, id_sqlite >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::persist_statement[] =
  "INSERT INTO \"NORTHWIND\".\"CATEGORIES\" "
  "(\"CATEGORY_ID\", "
  "\"CATEGORY_NAME\", "
  "\"DESCRIPTION\", "
  "\"PICUTRE\") "
  "VALUES "
  "(?, ?, ?, ?)";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::find_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"CATEGORIES\".\"CATEGORY_ID\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"CATEGORY_NAME\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"DESCRIPTION\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"PICUTRE\" "
  "FROM \"NORTHWIND\".\"CATEGORIES\" "
  "WHERE \"NORTHWIND\".\"CATEGORIES\".\"CATEGORY_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::update_statement[] =
  "UPDATE \"NORTHWIND\".\"CATEGORIES\" "
  "SET "
  "\"CATEGORY_NAME\"=?, "
  "\"DESCRIPTION\"=?, "
  "\"PICUTRE\"=? "
  "WHERE \"CATEGORY_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::erase_statement[] =
  "DELETE FROM \"NORTHWIND\".\"CATEGORIES\" "
  "WHERE \"CATEGORY_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::query_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"CATEGORIES\".\"CATEGORY_ID\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"CATEGORY_NAME\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"DESCRIPTION\", "
  "\"NORTHWIND\".\"CATEGORIES\".\"PICUTRE\" "
  "FROM \"NORTHWIND\".\"CATEGORIES\"";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"NORTHWIND\".\"CATEGORIES\"";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::table_name[] =
  "\"NORTHWIND\".\"CATEGORIES\"";

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::pointer_type
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::object_type >
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::masd::cpp_ref_impl::northwind::categories, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"NORTHWIND\".\"CATEGORIES\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"NORTHWIND\".\"CATEGORIES\" (\n"
                      "  \"CATEGORY_ID\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"CATEGORY_NAME\" TEXT NOT NULL,\n"
                      "  \"DESCRIPTION\" TEXT NULL,\n"
                      "  \"PICUTRE\" TEXT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
