// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "masd.cpp_ref_impl.northwind/odb/order_details_key-odb-sqlite.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>

namespace odb
{
  // order_details_key
  //

  bool access::composite_value_traits< ::masd::cpp_ref_impl::northwind::order_details_key, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // order_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::grow (
          i.order_id_value, t + 0UL))
      grew = true;

    // product_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::product_id, id_sqlite >::grow (
          i.product_id_value, t + 1UL))
      grew = true;

    return grew;
  }

  void access::composite_value_traits< ::masd::cpp_ref_impl::northwind::order_details_key, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // order_id_
    //
    composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::bind (
      b + n, i.order_id_value, sk);
    n += 1UL;

    // product_id_
    //
    composite_value_traits< ::masd::cpp_ref_impl::northwind::product_id, id_sqlite >::bind (
      b + n, i.product_id_value, sk);
    n += 1UL;
  }

  bool access::composite_value_traits< ::masd::cpp_ref_impl::northwind::order_details_key, id_sqlite >::
  init (image_type& i,
        const value_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // order_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::order_id const& v =
        o.order_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        i.order_id_value,
        v,
        sk);
    }

    // product_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::product_id const& v =
        o.product_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::product_id, id_sqlite >::init (
        i.product_id_value,
        v,
        sk);
    }

    return grew;
  }

  void access::composite_value_traits< ::masd::cpp_ref_impl::northwind::order_details_key, id_sqlite >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // order_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::order_id& v =
        o.order_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        v,
        i.order_id_value,
        db);
    }

    // product_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::product_id& v =
        o.product_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::product_id, id_sqlite >::init (
        v,
        i.product_id_value,
        db);
    }
  }
}

#include <odb/post.hxx>
