// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "masd.cpp_ref_impl.northwind/odb/orders-odb-sqlite.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // orders
  //

  struct access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::id_type
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        id,
        i.order_id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // order_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::grow (
          i.order_id_value, t + 0UL))
      grew = true;

    // customer_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::customer_id, id_sqlite >::grow (
          i.customer_id_value, t + 1UL))
      grew = true;

    // employee_id_
    //
    if (composite_value_traits< ::masd::cpp_ref_impl::northwind::employee_id, id_sqlite >::grow (
          i.employee_id_value, t + 2UL))
      grew = true;

    // order_date_
    //
    if (t[3UL])
    {
      i.order_date_value.capacity (i.order_date_size);
      grew = true;
    }

    // required_date_
    //
    if (t[4UL])
    {
      i.required_date_value.capacity (i.required_date_size);
      grew = true;
    }

    // shipped_date_
    //
    if (t[5UL])
    {
      i.shipped_date_value.capacity (i.shipped_date_size);
      grew = true;
    }

    // ship_via_
    //
    t[6UL] = false;

    // freight_
    //
    t[7UL] = false;

    // ship_name_
    //
    if (t[8UL])
    {
      i.ship_name_value.capacity (i.ship_name_size);
      grew = true;
    }

    // ship_address_
    //
    if (t[9UL])
    {
      i.ship_address_value.capacity (i.ship_address_size);
      grew = true;
    }

    // ship_city_
    //
    if (t[10UL])
    {
      i.ship_city_value.capacity (i.ship_city_size);
      grew = true;
    }

    // ship_region_
    //
    if (t[11UL])
    {
      i.ship_region_value.capacity (i.ship_region_size);
      grew = true;
    }

    // ship_postal_code_
    //
    if (t[12UL])
    {
      i.ship_postal_code_value.capacity (i.ship_postal_code_size);
      grew = true;
    }

    // ship_country_
    //
    if (t[13UL])
    {
      i.ship_country_value.capacity (i.ship_country_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // order_id_
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::bind (
        b + n, i.order_id_value, sk);
      n += 1UL;
    }

    // customer_id_
    //
    composite_value_traits< ::masd::cpp_ref_impl::northwind::customer_id, id_sqlite >::bind (
      b + n, i.customer_id_value, sk);
    n += 1UL;

    // employee_id_
    //
    composite_value_traits< ::masd::cpp_ref_impl::northwind::employee_id, id_sqlite >::bind (
      b + n, i.employee_id_value, sk);
    n += 1UL;

    // order_date_
    //
    b[n].type = sqlite::image_traits<
      ::boost::gregorian::date,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.order_date_value.data ();
    b[n].size = &i.order_date_size;
    b[n].capacity = i.order_date_value.capacity ();
    b[n].is_null = &i.order_date_null;
    n++;

    // required_date_
    //
    b[n].type = sqlite::image_traits<
      ::boost::gregorian::date,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.required_date_value.data ();
    b[n].size = &i.required_date_size;
    b[n].capacity = i.required_date_value.capacity ();
    b[n].is_null = &i.required_date_null;
    n++;

    // shipped_date_
    //
    b[n].type = sqlite::image_traits<
      ::boost::gregorian::date,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.shipped_date_value.data ();
    b[n].size = &i.shipped_date_size;
    b[n].capacity = i.shipped_date_value.capacity ();
    b[n].is_null = &i.shipped_date_null;
    n++;

    // ship_via_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.ship_via_value;
    b[n].is_null = &i.ship_via_null;
    n++;

    // freight_
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.freight_value;
    b[n].is_null = &i.freight_null;
    n++;

    // ship_name_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_name_value.data ();
    b[n].size = &i.ship_name_size;
    b[n].capacity = i.ship_name_value.capacity ();
    b[n].is_null = &i.ship_name_null;
    n++;

    // ship_address_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_address_value.data ();
    b[n].size = &i.ship_address_size;
    b[n].capacity = i.ship_address_value.capacity ();
    b[n].is_null = &i.ship_address_null;
    n++;

    // ship_city_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_city_value.data ();
    b[n].size = &i.ship_city_size;
    b[n].capacity = i.ship_city_value.capacity ();
    b[n].is_null = &i.ship_city_null;
    n++;

    // ship_region_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_region_value.data ();
    b[n].size = &i.ship_region_size;
    b[n].capacity = i.ship_region_value.capacity ();
    b[n].is_null = &i.ship_region_null;
    n++;

    // ship_postal_code_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_postal_code_value.data ();
    b[n].size = &i.ship_postal_code_size;
    b[n].capacity = i.ship_postal_code_value.capacity ();
    b[n].is_null = &i.ship_postal_code_null;
    n++;

    // ship_country_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ship_country_value.data ();
    b[n].size = &i.ship_country_size;
    b[n].capacity = i.ship_country_value.capacity ();
    b[n].is_null = &i.ship_country_null;
    n++;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    sqlite::statement_kind sk (sqlite::statement_select);
    composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // order_id_
    //
    if (sk == statement_insert)
    {
      ::masd::cpp_ref_impl::northwind::order_id const& v =
        o.order_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        i.order_id_value,
        v,
        sk);
    }

    // customer_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::customer_id const& v =
        o.customer_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        i.customer_id_value,
        v,
        sk);
    }

    // employee_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::employee_id const& v =
        o.employee_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::employee_id, id_sqlite >::init (
        i.employee_id_value,
        v,
        sk);
    }

    // order_date_
    //
    {
      ::boost::gregorian::date const& v =
        o.order_date ();

      bool is_null (true);
      std::size_t cap (i.order_date_value.capacity ());
      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_image (
        i.order_date_value,
        i.order_date_size,
        is_null,
        v);
      i.order_date_null = is_null;
      grew = grew || (cap != i.order_date_value.capacity ());
    }

    // required_date_
    //
    {
      ::boost::gregorian::date const& v =
        o.required_date ();

      bool is_null (true);
      std::size_t cap (i.required_date_value.capacity ());
      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_image (
        i.required_date_value,
        i.required_date_size,
        is_null,
        v);
      i.required_date_null = is_null;
      grew = grew || (cap != i.required_date_value.capacity ());
    }

    // shipped_date_
    //
    {
      ::boost::gregorian::date const& v =
        o.shipped_date ();

      bool is_null (true);
      std::size_t cap (i.shipped_date_value.capacity ());
      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_image (
        i.shipped_date_value,
        i.shipped_date_size,
        is_null,
        v);
      i.shipped_date_null = is_null;
      grew = grew || (cap != i.shipped_date_value.capacity ());
    }

    // ship_via_
    //
    {
      int const& v =
        o.ship_via ();

      bool is_null (true);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.ship_via_value,
        is_null,
        v);
      i.ship_via_null = is_null;
    }

    // freight_
    //
    {
      double const& v =
        o.freight ();

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.freight_value,
        is_null,
        v);
      i.freight_null = is_null;
    }

    // ship_name_
    //
    {
      ::std::string const& v =
        o.ship_name ();

      bool is_null (true);
      std::size_t cap (i.ship_name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_name_value,
        i.ship_name_size,
        is_null,
        v);
      i.ship_name_null = is_null;
      grew = grew || (cap != i.ship_name_value.capacity ());
    }

    // ship_address_
    //
    {
      ::std::string const& v =
        o.ship_address ();

      bool is_null (true);
      std::size_t cap (i.ship_address_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_address_value,
        i.ship_address_size,
        is_null,
        v);
      i.ship_address_null = is_null;
      grew = grew || (cap != i.ship_address_value.capacity ());
    }

    // ship_city_
    //
    {
      ::std::string const& v =
        o.ship_city ();

      bool is_null (true);
      std::size_t cap (i.ship_city_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_city_value,
        i.ship_city_size,
        is_null,
        v);
      i.ship_city_null = is_null;
      grew = grew || (cap != i.ship_city_value.capacity ());
    }

    // ship_region_
    //
    {
      ::std::string const& v =
        o.ship_region ();

      bool is_null (true);
      std::size_t cap (i.ship_region_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_region_value,
        i.ship_region_size,
        is_null,
        v);
      i.ship_region_null = is_null;
      grew = grew || (cap != i.ship_region_value.capacity ());
    }

    // ship_postal_code_
    //
    {
      ::std::string const& v =
        o.ship_postal_code ();

      bool is_null (true);
      std::size_t cap (i.ship_postal_code_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_postal_code_value,
        i.ship_postal_code_size,
        is_null,
        v);
      i.ship_postal_code_null = is_null;
      grew = grew || (cap != i.ship_postal_code_value.capacity ());
    }

    // ship_country_
    //
    {
      ::std::string const& v =
        o.ship_country ();

      bool is_null (true);
      std::size_t cap (i.ship_country_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ship_country_value,
        i.ship_country_size,
        is_null,
        v);
      i.ship_country_null = is_null;
      grew = grew || (cap != i.ship_country_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // order_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::order_id& v =
        o.order_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        v,
        i.order_id_value,
        db);
    }

    // customer_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::customer_id& v =
        o.customer_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        v,
        i.customer_id_value,
        db);
    }

    // employee_id_
    //
    {
      ::masd::cpp_ref_impl::northwind::employee_id& v =
        o.employee_id ();

      composite_value_traits< ::masd::cpp_ref_impl::northwind::employee_id, id_sqlite >::init (
        v,
        i.employee_id_value,
        db);
    }

    // order_date_
    //
    {
      ::boost::gregorian::date& v =
        o.order_date ();

      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_value (
        v,
        i.order_date_value,
        i.order_date_size,
        i.order_date_null);
    }

    // required_date_
    //
    {
      ::boost::gregorian::date& v =
        o.required_date ();

      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_value (
        v,
        i.required_date_value,
        i.required_date_size,
        i.required_date_null);
    }

    // shipped_date_
    //
    {
      ::boost::gregorian::date& v =
        o.shipped_date ();

      sqlite::value_traits<
          ::boost::gregorian::date,
          sqlite::id_text >::set_value (
        v,
        i.shipped_date_value,
        i.shipped_date_size,
        i.shipped_date_null);
    }

    // ship_via_
    //
    {
      int v;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.ship_via_value,
        i.ship_via_null);

      o.ship_via (v);
    }

    // freight_
    //
    {
      double v;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.freight_value,
        i.freight_null);

      o.freight (v);
    }

    // ship_name_
    //
    {
      ::std::string& v =
        o.ship_name ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_name_value,
        i.ship_name_size,
        i.ship_name_null);
    }

    // ship_address_
    //
    {
      ::std::string& v =
        o.ship_address ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_address_value,
        i.ship_address_size,
        i.ship_address_null);
    }

    // ship_city_
    //
    {
      ::std::string& v =
        o.ship_city ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_city_value,
        i.ship_city_size,
        i.ship_city_null);
    }

    // ship_region_
    //
    {
      ::std::string& v =
        o.ship_region ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_region_value,
        i.ship_region_size,
        i.ship_region_null);
    }

    // ship_postal_code_
    //
    {
      ::std::string& v =
        o.ship_postal_code ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_postal_code_value,
        i.ship_postal_code_size,
        i.ship_postal_code_null);
    }

    // ship_country_
    //
    {
      ::std::string& v =
        o.ship_country ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ship_country_value,
        i.ship_country_size,
        i.ship_country_null);
    }
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    sqlite::statement_kind sk (sqlite::statement_select);
    {
      composite_value_traits< ::masd::cpp_ref_impl::northwind::order_id, id_sqlite >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::persist_statement[] =
  "INSERT INTO \"NORTHWIND\".\"ORDERS\" "
  "(\"ORDER_ID\", "
  "\"CUSTOMER_ID\", "
  "\"EMPLOYEE_ID\", "
  "\"ORDER_DATE\", "
  "\"REQUIRED_DATE\", "
  "\"SHIPPED_DATE\", "
  "\"SHIP_VIA\", "
  "\"FREIGHT\", "
  "\"SHIP_NAME\", "
  "\"SHIP_ADDRESS\", "
  "\"SHIP_CITY\", "
  "\"SHIP_REGION\", "
  "\"SHIP_POSTAL_CODE\", "
  "\"SHIP_COUNTRY\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::find_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"ORDERS\".\"ORDER_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"CUSTOMER_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"EMPLOYEE_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"ORDER_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"REQUIRED_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIPPED_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_VIA\", "
  "\"NORTHWIND\".\"ORDERS\".\"FREIGHT\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_NAME\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_ADDRESS\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_CITY\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_REGION\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_POSTAL_CODE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_COUNTRY\" "
  "FROM \"NORTHWIND\".\"ORDERS\" "
  "WHERE \"NORTHWIND\".\"ORDERS\".\"ORDER_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::update_statement[] =
  "UPDATE \"NORTHWIND\".\"ORDERS\" "
  "SET "
  "\"CUSTOMER_ID\"=?, "
  "\"EMPLOYEE_ID\"=?, "
  "\"ORDER_DATE\"=?, "
  "\"REQUIRED_DATE\"=?, "
  "\"SHIPPED_DATE\"=?, "
  "\"SHIP_VIA\"=?, "
  "\"FREIGHT\"=?, "
  "\"SHIP_NAME\"=?, "
  "\"SHIP_ADDRESS\"=?, "
  "\"SHIP_CITY\"=?, "
  "\"SHIP_REGION\"=?, "
  "\"SHIP_POSTAL_CODE\"=?, "
  "\"SHIP_COUNTRY\"=? "
  "WHERE \"ORDER_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::erase_statement[] =
  "DELETE FROM \"NORTHWIND\".\"ORDERS\" "
  "WHERE \"ORDER_ID\"=?";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::query_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"ORDERS\".\"ORDER_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"CUSTOMER_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"EMPLOYEE_ID\", "
  "\"NORTHWIND\".\"ORDERS\".\"ORDER_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"REQUIRED_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIPPED_DATE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_VIA\", "
  "\"NORTHWIND\".\"ORDERS\".\"FREIGHT\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_NAME\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_ADDRESS\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_CITY\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_REGION\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_POSTAL_CODE\", "
  "\"NORTHWIND\".\"ORDERS\".\"SHIP_COUNTRY\" "
  "FROM \"NORTHWIND\".\"ORDERS\"";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"NORTHWIND\".\"ORDERS\"";

  const char access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::table_name[] =
  "\"NORTHWIND\".\"ORDERS\"";

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::pointer_type
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::object_type >
  access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::masd::cpp_ref_impl::northwind::orders, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"NORTHWIND\".\"ORDERS\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"NORTHWIND\".\"ORDERS\" (\n"
                      "  \"ORDER_ID\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"CUSTOMER_ID\" INTEGER NULL,\n"
                      "  \"EMPLOYEE_ID\" INTEGER NULL,\n"
                      "  \"ORDER_DATE\" TEXT NULL,\n"
                      "  \"REQUIRED_DATE\" TEXT NULL,\n"
                      "  \"SHIPPED_DATE\" TEXT NULL,\n"
                      "  \"SHIP_VIA\" INTEGER NULL,\n"
                      "  \"FREIGHT\" REAL NULL,\n"
                      "  \"SHIP_NAME\" TEXT NULL,\n"
                      "  \"SHIP_ADDRESS\" TEXT NULL,\n"
                      "  \"SHIP_CITY\" TEXT NULL,\n"
                      "  \"SHIP_REGION\" TEXT NULL,\n"
                      "  \"SHIP_POSTAL_CODE\" TEXT NULL,\n"
                      "  \"SHIP_COUNTRY\" TEXT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
