/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * This is a code-generated file.
 *
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.25
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include <ostream>
#include "cpp_ref_impl.lam_model/io/package1/class_in_package_io.hpp"

namespace cpp_ref_impl::lam_model::package1 {

std::ostream& operator<<(std::ostream& s, const class_in_package& v) {
    s << " { "
      << "\"__type__\": " << "\"cpp_ref_impl::lam_model::package1::class_in_package\"" << ", "
      << "\"prop_0\": " << v.prop_0()
      << " }";
    return(s);
}

}
