// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "cpp_ref_impl.northwind/odb/customers-odb-sqlite.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // customers
  //

  struct access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::id_type
  access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        id,
        i.customer_id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // customer_id_
    //
    if (composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::grow (
          i.customer_id_value, t + 0UL))
      grew = true;

    // customer_code_
    //
    if (t[1UL])
    {
      i.customer_code_value.capacity (i.customer_code_size);
      grew = true;
    }

    // company_name_
    //
    if (t[2UL])
    {
      i.company_name_value.capacity (i.company_name_size);
      grew = true;
    }

    // contact_name_
    //
    if (t[3UL])
    {
      i.contact_name_value.capacity (i.contact_name_size);
      grew = true;
    }

    // contact_title_
    //
    if (t[4UL])
    {
      i.contact_title_value.capacity (i.contact_title_size);
      grew = true;
    }

    // address_
    //
    if (t[5UL])
    {
      i.address_value.capacity (i.address_size);
      grew = true;
    }

    // city_
    //
    if (t[6UL])
    {
      i.city_value.capacity (i.city_size);
      grew = true;
    }

    // region_
    //
    if (t[7UL])
    {
      i.region_value.capacity (i.region_size);
      grew = true;
    }

    // postal_code_
    //
    if (t[8UL])
    {
      i.postal_code_value.capacity (i.postal_code_size);
      grew = true;
    }

    // country_
    //
    if (t[9UL])
    {
      i.country_value.capacity (i.country_size);
      grew = true;
    }

    // phone_
    //
    if (t[10UL])
    {
      i.phone_value.capacity (i.phone_size);
      grew = true;
    }

    // fax_
    //
    if (t[11UL])
    {
      i.fax_value.capacity (i.fax_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // customer_id_
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::bind (
        b + n, i.customer_id_value, sk);
      n += 1UL;
    }

    // customer_code_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.customer_code_value.data ();
    b[n].size = &i.customer_code_size;
    b[n].capacity = i.customer_code_value.capacity ();
    b[n].is_null = &i.customer_code_null;
    n++;

    // company_name_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.company_name_value.data ();
    b[n].size = &i.company_name_size;
    b[n].capacity = i.company_name_value.capacity ();
    b[n].is_null = &i.company_name_null;
    n++;

    // contact_name_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.contact_name_value.data ();
    b[n].size = &i.contact_name_size;
    b[n].capacity = i.contact_name_value.capacity ();
    b[n].is_null = &i.contact_name_null;
    n++;

    // contact_title_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.contact_title_value.data ();
    b[n].size = &i.contact_title_size;
    b[n].capacity = i.contact_title_value.capacity ();
    b[n].is_null = &i.contact_title_null;
    n++;

    // address_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.address_value.data ();
    b[n].size = &i.address_size;
    b[n].capacity = i.address_value.capacity ();
    b[n].is_null = &i.address_null;
    n++;

    // city_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.city_value.data ();
    b[n].size = &i.city_size;
    b[n].capacity = i.city_value.capacity ();
    b[n].is_null = &i.city_null;
    n++;

    // region_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.region_value.data ();
    b[n].size = &i.region_size;
    b[n].capacity = i.region_value.capacity ();
    b[n].is_null = &i.region_null;
    n++;

    // postal_code_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.postal_code_value.data ();
    b[n].size = &i.postal_code_size;
    b[n].capacity = i.postal_code_value.capacity ();
    b[n].is_null = &i.postal_code_null;
    n++;

    // country_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.country_value.data ();
    b[n].size = &i.country_size;
    b[n].capacity = i.country_value.capacity ();
    b[n].is_null = &i.country_null;
    n++;

    // phone_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.phone_value.data ();
    b[n].size = &i.phone_size;
    b[n].capacity = i.phone_value.capacity ();
    b[n].is_null = &i.phone_null;
    n++;

    // fax_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.fax_value.data ();
    b[n].size = &i.fax_size;
    b[n].capacity = i.fax_value.capacity ();
    b[n].is_null = &i.fax_null;
    n++;
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    sqlite::statement_kind sk (sqlite::statement_select);
    composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // customer_id_
    //
    if (sk == statement_insert)
    {
      ::cpp_ref_impl::northwind::customer_id const& v =
        o.customer_id ();

      composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        i.customer_id_value,
        v,
        sk);
    }

    // customer_code_
    //
    {
      ::std::string const& v =
        o.customer_code ();

      bool is_null (false);
      std::size_t cap (i.customer_code_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.customer_code_value,
        i.customer_code_size,
        is_null,
        v);
      i.customer_code_null = is_null;
      grew = grew || (cap != i.customer_code_value.capacity ());
    }

    // company_name_
    //
    {
      ::std::string const& v =
        o.company_name ();

      bool is_null (false);
      std::size_t cap (i.company_name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.company_name_value,
        i.company_name_size,
        is_null,
        v);
      i.company_name_null = is_null;
      grew = grew || (cap != i.company_name_value.capacity ());
    }

    // contact_name_
    //
    {
      ::std::string const& v =
        o.contact_name ();

      bool is_null (true);
      std::size_t cap (i.contact_name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.contact_name_value,
        i.contact_name_size,
        is_null,
        v);
      i.contact_name_null = is_null;
      grew = grew || (cap != i.contact_name_value.capacity ());
    }

    // contact_title_
    //
    {
      ::std::string const& v =
        o.contact_title ();

      bool is_null (true);
      std::size_t cap (i.contact_title_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.contact_title_value,
        i.contact_title_size,
        is_null,
        v);
      i.contact_title_null = is_null;
      grew = grew || (cap != i.contact_title_value.capacity ());
    }

    // address_
    //
    {
      ::std::string const& v =
        o.address ();

      bool is_null (true);
      std::size_t cap (i.address_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.address_value,
        i.address_size,
        is_null,
        v);
      i.address_null = is_null;
      grew = grew || (cap != i.address_value.capacity ());
    }

    // city_
    //
    {
      ::std::string const& v =
        o.city ();

      bool is_null (true);
      std::size_t cap (i.city_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.city_value,
        i.city_size,
        is_null,
        v);
      i.city_null = is_null;
      grew = grew || (cap != i.city_value.capacity ());
    }

    // region_
    //
    {
      ::std::string const& v =
        o.region ();

      bool is_null (true);
      std::size_t cap (i.region_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.region_value,
        i.region_size,
        is_null,
        v);
      i.region_null = is_null;
      grew = grew || (cap != i.region_value.capacity ());
    }

    // postal_code_
    //
    {
      ::std::string const& v =
        o.postal_code ();

      bool is_null (true);
      std::size_t cap (i.postal_code_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.postal_code_value,
        i.postal_code_size,
        is_null,
        v);
      i.postal_code_null = is_null;
      grew = grew || (cap != i.postal_code_value.capacity ());
    }

    // country_
    //
    {
      ::std::string const& v =
        o.country ();

      bool is_null (true);
      std::size_t cap (i.country_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.country_value,
        i.country_size,
        is_null,
        v);
      i.country_null = is_null;
      grew = grew || (cap != i.country_value.capacity ());
    }

    // phone_
    //
    {
      ::std::string const& v =
        o.phone ();

      bool is_null (true);
      std::size_t cap (i.phone_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.phone_value,
        i.phone_size,
        is_null,
        v);
      i.phone_null = is_null;
      grew = grew || (cap != i.phone_value.capacity ());
    }

    // fax_
    //
    {
      ::std::string const& v =
        o.fax ();

      bool is_null (true);
      std::size_t cap (i.fax_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.fax_value,
        i.fax_size,
        is_null,
        v);
      i.fax_null = is_null;
      grew = grew || (cap != i.fax_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // customer_id_
    //
    {
      ::cpp_ref_impl::northwind::customer_id& v =
        o.customer_id ();

      composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        v,
        i.customer_id_value,
        db);
    }

    // customer_code_
    //
    {
      ::std::string& v =
        o.customer_code ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.customer_code_value,
        i.customer_code_size,
        i.customer_code_null);
    }

    // company_name_
    //
    {
      ::std::string& v =
        o.company_name ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.company_name_value,
        i.company_name_size,
        i.company_name_null);
    }

    // contact_name_
    //
    {
      ::std::string& v =
        o.contact_name ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.contact_name_value,
        i.contact_name_size,
        i.contact_name_null);
    }

    // contact_title_
    //
    {
      ::std::string& v =
        o.contact_title ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.contact_title_value,
        i.contact_title_size,
        i.contact_title_null);
    }

    // address_
    //
    {
      ::std::string& v =
        o.address ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.address_value,
        i.address_size,
        i.address_null);
    }

    // city_
    //
    {
      ::std::string& v =
        o.city ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.city_value,
        i.city_size,
        i.city_null);
    }

    // region_
    //
    {
      ::std::string& v =
        o.region ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.region_value,
        i.region_size,
        i.region_null);
    }

    // postal_code_
    //
    {
      ::std::string& v =
        o.postal_code ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.postal_code_value,
        i.postal_code_size,
        i.postal_code_null);
    }

    // country_
    //
    {
      ::std::string& v =
        o.country ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.country_value,
        i.country_size,
        i.country_null);
    }

    // phone_
    //
    {
      ::std::string& v =
        o.phone ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.phone_value,
        i.phone_size,
        i.phone_null);
    }

    // fax_
    //
    {
      ::std::string& v =
        o.fax ();

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.fax_value,
        i.fax_size,
        i.fax_null);
    }
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    sqlite::statement_kind sk (sqlite::statement_select);
    {
      composite_value_traits< ::cpp_ref_impl::northwind::customer_id, id_sqlite >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::persist_statement[] =
  "INSERT INTO \"NORTHWIND\".\"CUSTOMERS\" "
  "(\"CUSTOMER_ID\", "
  "\"CUSTOMER_CODE\", "
  "\"COMPANY_NAME\", "
  "\"CONTACT_NAME\", "
  "\"CONTACT_TITLE\", "
  "\"ADDRESS\", "
  "\"CITY\", "
  "\"REGION\", "
  "\"POSTAL_CODE\", "
  "\"COUNTRY\", "
  "\"PHONE\", "
  "\"FAX\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::find_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CUSTOMER_ID\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CUSTOMER_CODE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"COMPANY_NAME\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CONTACT_NAME\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CONTACT_TITLE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"ADDRESS\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CITY\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"REGION\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"POSTAL_CODE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"COUNTRY\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"PHONE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"FAX\" "
  "FROM \"NORTHWIND\".\"CUSTOMERS\" "
  "WHERE \"NORTHWIND\".\"CUSTOMERS\".\"CUSTOMER_ID\"=?";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::update_statement[] =
  "UPDATE \"NORTHWIND\".\"CUSTOMERS\" "
  "SET "
  "\"CUSTOMER_CODE\"=?, "
  "\"COMPANY_NAME\"=?, "
  "\"CONTACT_NAME\"=?, "
  "\"CONTACT_TITLE\"=?, "
  "\"ADDRESS\"=?, "
  "\"CITY\"=?, "
  "\"REGION\"=?, "
  "\"POSTAL_CODE\"=?, "
  "\"COUNTRY\"=?, "
  "\"PHONE\"=?, "
  "\"FAX\"=? "
  "WHERE \"CUSTOMER_ID\"=?";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::erase_statement[] =
  "DELETE FROM \"NORTHWIND\".\"CUSTOMERS\" "
  "WHERE \"CUSTOMER_ID\"=?";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::query_statement[] =
  "SELECT "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CUSTOMER_ID\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CUSTOMER_CODE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"COMPANY_NAME\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CONTACT_NAME\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CONTACT_TITLE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"ADDRESS\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"CITY\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"REGION\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"POSTAL_CODE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"COUNTRY\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"PHONE\", "
  "\"NORTHWIND\".\"CUSTOMERS\".\"FAX\" "
  "FROM \"NORTHWIND\".\"CUSTOMERS\"";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"NORTHWIND\".\"CUSTOMERS\"";

  const char access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::table_name[] =
  "\"NORTHWIND\".\"CUSTOMERS\"";

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::pointer_type
  access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::object_type >
  access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::cpp_ref_impl::northwind::customers, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"NORTHWIND\".\"CUSTOMERS\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"NORTHWIND\".\"CUSTOMERS\" (\n"
                      "  \"CUSTOMER_ID\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"CUSTOMER_CODE\" TEXT NOT NULL,\n"
                      "  \"COMPANY_NAME\" TEXT NOT NULL,\n"
                      "  \"CONTACT_NAME\" TEXT NULL,\n"
                      "  \"CONTACT_TITLE\" TEXT NULL,\n"
                      "  \"ADDRESS\" TEXT NULL,\n"
                      "  \"CITY\" TEXT NULL,\n"
                      "  \"REGION\" TEXT NULL,\n"
                      "  \"POSTAL_CODE\" TEXT NULL,\n"
                      "  \"COUNTRY\" TEXT NULL,\n"
                      "  \"PHONE\" TEXT NULL,\n"
                      "  \"FAX\" TEXT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
